networks:
  ksqldb_test_network:
    driver: bridge

volumes:
  redpanda-0: null

services:

  ksqldb-ui:
    image: deniskrumko/ksqldb-ui:latest
    # build: .
    environment:
      APP_CONFIG: /config.toml
      KSQLDB_UI__SERVERS__LOCALHOST__URL: http://ksqldb:8088
      KSQLDB_UI__SERVERS__LOCALHOST__TOPIC_LINK: http://localhost:8090/topics/{}
    networks:
      - ksqldb_test_network
    ports:
      - 8080:8080

  ksqldb:
    image: confluentinc/cp-ksqldb-server:7.6.1
    ports:
      - "8088:8088"
    depends_on:
      - redpanda-0
    networks:
      - ksqldb_test_network
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_BOOTSTRAP_SERVERS: redpanda-0:9092
      # KSQL_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      # KSQL_SASL_MECHANISM: "SCRAM-SHA-256"
      # KSQL_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"$REDPANDA_USER\" password=\"$REDPANDA_PASSWORD\";"
      # KSQL_PRODUCER_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      # KSQL_PRODUCER_SASL_MECHANISM: "SCRAM-SHA-256"
      # KSQL_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"$REDPANDA_USER\" password=\"$REDPANDA_PASSWORD\";"
      # KSQL_CONSUMER_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      # KSQL_CONSUMER_SASL_MECHANISM: "SCRAM-SHA-256"
      # KSQL_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"$REDPANDA_USER\" password=\"$REDPANDA_PASSWORD\";"
      KSQL_COMPRESSION_TYPE: "snappy"
      KSQL_KSQL_STREAM_PRODUCER_DELIVERY_TIMEOUT_MS: "2147483647"
      KSQL_KSQL_STREAM_PRODUCER_MAX_BLOCK_MS: "9223372036854775807"
      KSQL_KSQL_INTERNAL_TOPIC_REPLICAS: "1"
      KSQL_KSQL_INTERNAL_TOPIC_MIN_INSYNC_REPLICAS: "2"
      KSQL_KSQL_STREAMS_REPLICATION_FACTOR: "1"
      KSQL_KSQL_STREAMS_PRODUCER_ACKS: "all"
      KSQL_KSQL_STREAMS_TOPIC_MIN_INSYNC_REPLICAS: "2"
      KSQL_KSQL_STREAMS_NUM_STANDBY_REPLICAS: "1"
      KSQL_KSQL_SERVICE_ID: "ksql-local-test-server"
      KSQL_KSQL_EXTENSION_DIR: "/opt/ksql/ext/"
      KSQL_INIT_SCRIPT_PATH: "/opt/ksql/scripts/local/common.sql"

  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=debug
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.12
    container_name: redpanda-0
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    networks:
      - ksqldb_test_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644

  redpanda-console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    ports:
      - 8090:8080
    depends_on:
      - redpanda-0
    networks:
      - ksqldb_test_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
